version: '3'
services:
  db:
    image: "mdillon/postgis"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - env_file
    networks:
      - db_nw
    ports:
      - 5433:5432
  flaskapp:
    build: .
    #    command: python3 -c "from ministac.db import init_db; init_db();"
    volumes:
      - ".ministac:/root/.ministac"
    networks:
      - db_nw
    env_file:
      - env_file
    depends_on:
      - db
    ports:
      - 5000:5000
networks:
  db_nw:
    driver: bridge
volumes:
  dbdata:
